// Code generated by "enumer -type=StartingAge"; DO NOT EDIT.

package startingage

import (
	"fmt"
	"strings"
)

const _StartingAgeName = "ChildAdultRandom"

var _StartingAgeIndex = [...]uint8{0, 5, 10, 16}

const _StartingAgeLowerName = "childadultrandom"

func (i StartingAge) String() string {
	if i < 0 || i >= StartingAge(len(_StartingAgeIndex)-1) {
		return fmt.Sprintf("StartingAge(%d)", i)
	}
	return _StartingAgeName[_StartingAgeIndex[i]:_StartingAgeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _StartingAgeNoOp() {
	var x [1]struct{}
	_ = x[Child-(0)]
	_ = x[Adult-(1)]
	_ = x[Random-(2)]
}

var _StartingAgeValues = []StartingAge{Child, Adult, Random}

var _StartingAgeNameToValueMap = map[string]StartingAge{
	_StartingAgeName[0:5]:        Child,
	_StartingAgeLowerName[0:5]:   Child,
	_StartingAgeName[5:10]:       Adult,
	_StartingAgeLowerName[5:10]:  Adult,
	_StartingAgeName[10:16]:      Random,
	_StartingAgeLowerName[10:16]: Random,
}

var _StartingAgeNames = []string{
	_StartingAgeName[0:5],
	_StartingAgeName[5:10],
	_StartingAgeName[10:16],
}

// StartingAgeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func StartingAgeString(s string) (StartingAge, error) {
	if val, ok := _StartingAgeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _StartingAgeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to StartingAge values", s)
}

// StartingAgeValues returns all values of the enum
func StartingAgeValues() []StartingAge {
	return _StartingAgeValues
}

// StartingAgeStrings returns a slice of all String values of the enum
func StartingAgeStrings() []string {
	strs := make([]string, len(_StartingAgeNames))
	copy(strs, _StartingAgeNames)
	return strs
}

// IsAStartingAge returns "true" if the value is listed in the enum definition. "false" otherwise
func (i StartingAge) IsAStartingAge() bool {
	for _, v := range _StartingAgeValues {
		if i == v {
			return true
		}
	}
	return false
}
