// Code generated by "enumer -type=Shopsanity"; DO NOT EDIT.

package shopsanity

import (
	"fmt"
	"strings"
)

const _ShopsanityName = "OffZeroItemsOneItemTwoItemsThreeItemsFourItemsRandom"

var _ShopsanityIndex = [...]uint8{0, 3, 12, 19, 27, 37, 46, 52}

const _ShopsanityLowerName = "offzeroitemsoneitemtwoitemsthreeitemsfouritemsrandom"

func (i Shopsanity) String() string {
	if i < 0 || i >= Shopsanity(len(_ShopsanityIndex)-1) {
		return fmt.Sprintf("Shopsanity(%d)", i)
	}
	return _ShopsanityName[_ShopsanityIndex[i]:_ShopsanityIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ShopsanityNoOp() {
	var x [1]struct{}
	_ = x[Off-(0)]
	_ = x[ZeroItems-(1)]
	_ = x[OneItem-(2)]
	_ = x[TwoItems-(3)]
	_ = x[ThreeItems-(4)]
	_ = x[FourItems-(5)]
	_ = x[Random-(6)]
}

var _ShopsanityValues = []Shopsanity{Off, ZeroItems, OneItem, TwoItems, ThreeItems, FourItems, Random}

var _ShopsanityNameToValueMap = map[string]Shopsanity{
	_ShopsanityName[0:3]:        Off,
	_ShopsanityLowerName[0:3]:   Off,
	_ShopsanityName[3:12]:       ZeroItems,
	_ShopsanityLowerName[3:12]:  ZeroItems,
	_ShopsanityName[12:19]:      OneItem,
	_ShopsanityLowerName[12:19]: OneItem,
	_ShopsanityName[19:27]:      TwoItems,
	_ShopsanityLowerName[19:27]: TwoItems,
	_ShopsanityName[27:37]:      ThreeItems,
	_ShopsanityLowerName[27:37]: ThreeItems,
	_ShopsanityName[37:46]:      FourItems,
	_ShopsanityLowerName[37:46]: FourItems,
	_ShopsanityName[46:52]:      Random,
	_ShopsanityLowerName[46:52]: Random,
}

var _ShopsanityNames = []string{
	_ShopsanityName[0:3],
	_ShopsanityName[3:12],
	_ShopsanityName[12:19],
	_ShopsanityName[19:27],
	_ShopsanityName[27:37],
	_ShopsanityName[37:46],
	_ShopsanityName[46:52],
}

// ShopsanityString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ShopsanityString(s string) (Shopsanity, error) {
	if val, ok := _ShopsanityNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ShopsanityNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Shopsanity values", s)
}

// ShopsanityValues returns all values of the enum
func ShopsanityValues() []Shopsanity {
	return _ShopsanityValues
}

// ShopsanityStrings returns a slice of all String values of the enum
func ShopsanityStrings() []string {
	strs := make([]string, len(_ShopsanityNames))
	copy(strs, _ShopsanityNames)
	return strs
}

// IsAShopsanity returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Shopsanity) IsAShopsanity() bool {
	for _, v := range _ShopsanityValues {
		if i == v {
			return true
		}
	}
	return false
}
