// Code generated by "enumer -type=Tokensanity"; DO NOT EDIT.

package tokensanity

import (
	"fmt"
	"strings"
)

const _TokensanityName = "OffDungeonsOverworldAllTokens"

var _TokensanityIndex = [...]uint8{0, 3, 11, 20, 29}

const _TokensanityLowerName = "offdungeonsoverworldalltokens"

func (i Tokensanity) String() string {
	if i < 0 || i >= Tokensanity(len(_TokensanityIndex)-1) {
		return fmt.Sprintf("Tokensanity(%d)", i)
	}
	return _TokensanityName[_TokensanityIndex[i]:_TokensanityIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _TokensanityNoOp() {
	var x [1]struct{}
	_ = x[Off-(0)]
	_ = x[Dungeons-(1)]
	_ = x[Overworld-(2)]
	_ = x[AllTokens-(3)]
}

var _TokensanityValues = []Tokensanity{Off, Dungeons, Overworld, AllTokens}

var _TokensanityNameToValueMap = map[string]Tokensanity{
	_TokensanityName[0:3]:        Off,
	_TokensanityLowerName[0:3]:   Off,
	_TokensanityName[3:11]:       Dungeons,
	_TokensanityLowerName[3:11]:  Dungeons,
	_TokensanityName[11:20]:      Overworld,
	_TokensanityLowerName[11:20]: Overworld,
	_TokensanityName[20:29]:      AllTokens,
	_TokensanityLowerName[20:29]: AllTokens,
}

var _TokensanityNames = []string{
	_TokensanityName[0:3],
	_TokensanityName[3:11],
	_TokensanityName[11:20],
	_TokensanityName[20:29],
}

// TokensanityString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func TokensanityString(s string) (Tokensanity, error) {
	if val, ok := _TokensanityNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _TokensanityNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Tokensanity values", s)
}

// TokensanityValues returns all values of the enum
func TokensanityValues() []Tokensanity {
	return _TokensanityValues
}

// TokensanityStrings returns a slice of all String values of the enum
func TokensanityStrings() []string {
	strs := make([]string, len(_TokensanityNames))
	copy(strs, _TokensanityNames)
	return strs
}

// IsATokensanity returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Tokensanity) IsATokensanity() bool {
	for _, v := range _TokensanityValues {
		if i == v {
			return true
		}
	}
	return false
}
