// Code generated by "enumer -type=ItemPool"; DO NOT EDIT.

package itempool

import (
	"fmt"
	"strings"
)

const _ItemPoolName = "PlentifulBalancedScarceMinimal"

var _ItemPoolIndex = [...]uint8{0, 9, 17, 23, 30}

const _ItemPoolLowerName = "plentifulbalancedscarceminimal"

func (i ItemPool) String() string {
	if i < 0 || i >= ItemPool(len(_ItemPoolIndex)-1) {
		return fmt.Sprintf("ItemPool(%d)", i)
	}
	return _ItemPoolName[_ItemPoolIndex[i]:_ItemPoolIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ItemPoolNoOp() {
	var x [1]struct{}
	_ = x[Plentiful-(0)]
	_ = x[Balanced-(1)]
	_ = x[Scarce-(2)]
	_ = x[Minimal-(3)]
}

var _ItemPoolValues = []ItemPool{Plentiful, Balanced, Scarce, Minimal}

var _ItemPoolNameToValueMap = map[string]ItemPool{
	_ItemPoolName[0:9]:        Plentiful,
	_ItemPoolLowerName[0:9]:   Plentiful,
	_ItemPoolName[9:17]:       Balanced,
	_ItemPoolLowerName[9:17]:  Balanced,
	_ItemPoolName[17:23]:      Scarce,
	_ItemPoolLowerName[17:23]: Scarce,
	_ItemPoolName[23:30]:      Minimal,
	_ItemPoolLowerName[23:30]: Minimal,
}

var _ItemPoolNames = []string{
	_ItemPoolName[0:9],
	_ItemPoolName[9:17],
	_ItemPoolName[17:23],
	_ItemPoolName[23:30],
}

// ItemPoolString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ItemPoolString(s string) (ItemPool, error) {
	if val, ok := _ItemPoolNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ItemPoolNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ItemPool values", s)
}

// ItemPoolValues returns all values of the enum
func ItemPoolValues() []ItemPool {
	return _ItemPoolValues
}

// ItemPoolStrings returns a slice of all String values of the enum
func ItemPoolStrings() []string {
	strs := make([]string, len(_ItemPoolNames))
	copy(strs, _ItemPoolNames)
	return strs
}

// IsAItemPool returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ItemPool) IsAItemPool() bool {
	for _, v := range _ItemPoolValues {
		if i == v {
			return true
		}
	}
	return false
}
