// Code generated by "enumer -type=EntranceRando"; DO NOT EDIT.

package entrancerando

import (
	"fmt"
	"strings"
)

const _EntranceRandoName = "OffOn"

var _EntranceRandoIndex = [...]uint8{0, 3, 5}

const _EntranceRandoLowerName = "offon"

func (i EntranceRando) String() string {
	if i < 0 || i >= EntranceRando(len(_EntranceRandoIndex)-1) {
		return fmt.Sprintf("EntranceRando(%d)", i)
	}
	return _EntranceRandoName[_EntranceRandoIndex[i]:_EntranceRandoIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _EntranceRandoNoOp() {
	var x [1]struct{}
	_ = x[Off-(0)]
	_ = x[On-(1)]
}

var _EntranceRandoValues = []EntranceRando{Off, On}

var _EntranceRandoNameToValueMap = map[string]EntranceRando{
	_EntranceRandoName[0:3]:      Off,
	_EntranceRandoLowerName[0:3]: Off,
	_EntranceRandoName[3:5]:      On,
	_EntranceRandoLowerName[3:5]: On,
}

var _EntranceRandoNames = []string{
	_EntranceRandoName[0:3],
	_EntranceRandoName[3:5],
}

// EntranceRandoString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func EntranceRandoString(s string) (EntranceRando, error) {
	if val, ok := _EntranceRandoNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _EntranceRandoNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to EntranceRando values", s)
}

// EntranceRandoValues returns all values of the enum
func EntranceRandoValues() []EntranceRando {
	return _EntranceRandoValues
}

// EntranceRandoStrings returns a slice of all String values of the enum
func EntranceRandoStrings() []string {
	strs := make([]string, len(_EntranceRandoNames))
	copy(strs, _EntranceRandoNames)
	return strs
}

// IsAEntranceRando returns "true" if the value is listed in the enum definition. "false" otherwise
func (i EntranceRando) IsAEntranceRando() bool {
	for _, v := range _EntranceRandoValues {
		if i == v {
			return true
		}
	}
	return false
}
