// Code generated by "enumer -type=MQDungeons"; DO NOT EDIT.

package mqdungeons

import (
	"fmt"
	"strings"
)

const _MQDungeonsName = "SelectionRandomZeroOneTwoThreeFourFiveSixSevenEightNineTenElevenTwelve"

var _MQDungeonsIndex = [...]uint8{0, 9, 15, 19, 22, 25, 30, 34, 38, 41, 46, 51, 55, 58, 64, 70}

const _MQDungeonsLowerName = "selectionrandomzeroonetwothreefourfivesixseveneightnineteneleventwelve"

func (i MQDungeons) String() string {
	if i < 0 || i >= MQDungeons(len(_MQDungeonsIndex)-1) {
		return fmt.Sprintf("MQDungeons(%d)", i)
	}
	return _MQDungeonsName[_MQDungeonsIndex[i]:_MQDungeonsIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _MQDungeonsNoOp() {
	var x [1]struct{}
	_ = x[Selection-(0)]
	_ = x[Random-(1)]
	_ = x[Zero-(2)]
	_ = x[One-(3)]
	_ = x[Two-(4)]
	_ = x[Three-(5)]
	_ = x[Four-(6)]
	_ = x[Five-(7)]
	_ = x[Six-(8)]
	_ = x[Seven-(9)]
	_ = x[Eight-(10)]
	_ = x[Nine-(11)]
	_ = x[Ten-(12)]
	_ = x[Eleven-(13)]
	_ = x[Twelve-(14)]
}

var _MQDungeonsValues = []MQDungeons{Selection, Random, Zero, One, Two, Three, Four, Five, Six, Seven, Eight, Nine, Ten, Eleven, Twelve}

var _MQDungeonsNameToValueMap = map[string]MQDungeons{
	_MQDungeonsName[0:9]:        Selection,
	_MQDungeonsLowerName[0:9]:   Selection,
	_MQDungeonsName[9:15]:       Random,
	_MQDungeonsLowerName[9:15]:  Random,
	_MQDungeonsName[15:19]:      Zero,
	_MQDungeonsLowerName[15:19]: Zero,
	_MQDungeonsName[19:22]:      One,
	_MQDungeonsLowerName[19:22]: One,
	_MQDungeonsName[22:25]:      Two,
	_MQDungeonsLowerName[22:25]: Two,
	_MQDungeonsName[25:30]:      Three,
	_MQDungeonsLowerName[25:30]: Three,
	_MQDungeonsName[30:34]:      Four,
	_MQDungeonsLowerName[30:34]: Four,
	_MQDungeonsName[34:38]:      Five,
	_MQDungeonsLowerName[34:38]: Five,
	_MQDungeonsName[38:41]:      Six,
	_MQDungeonsLowerName[38:41]: Six,
	_MQDungeonsName[41:46]:      Seven,
	_MQDungeonsLowerName[41:46]: Seven,
	_MQDungeonsName[46:51]:      Eight,
	_MQDungeonsLowerName[46:51]: Eight,
	_MQDungeonsName[51:55]:      Nine,
	_MQDungeonsLowerName[51:55]: Nine,
	_MQDungeonsName[55:58]:      Ten,
	_MQDungeonsLowerName[55:58]: Ten,
	_MQDungeonsName[58:64]:      Eleven,
	_MQDungeonsLowerName[58:64]: Eleven,
	_MQDungeonsName[64:70]:      Twelve,
	_MQDungeonsLowerName[64:70]: Twelve,
}

var _MQDungeonsNames = []string{
	_MQDungeonsName[0:9],
	_MQDungeonsName[9:15],
	_MQDungeonsName[15:19],
	_MQDungeonsName[19:22],
	_MQDungeonsName[22:25],
	_MQDungeonsName[25:30],
	_MQDungeonsName[30:34],
	_MQDungeonsName[34:38],
	_MQDungeonsName[38:41],
	_MQDungeonsName[41:46],
	_MQDungeonsName[46:51],
	_MQDungeonsName[51:55],
	_MQDungeonsName[55:58],
	_MQDungeonsName[58:64],
	_MQDungeonsName[64:70],
}

// MQDungeonsString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func MQDungeonsString(s string) (MQDungeons, error) {
	if val, ok := _MQDungeonsNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _MQDungeonsNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to MQDungeons values", s)
}

// MQDungeonsValues returns all values of the enum
func MQDungeonsValues() []MQDungeons {
	return _MQDungeonsValues
}

// MQDungeonsStrings returns a slice of all String values of the enum
func MQDungeonsStrings() []string {
	strs := make([]string, len(_MQDungeonsNames))
	copy(strs, _MQDungeonsNames)
	return strs
}

// IsAMQDungeons returns "true" if the value is listed in the enum definition. "false" otherwise
func (i MQDungeons) IsAMQDungeons() bool {
	for _, v := range _MQDungeonsValues {
		if i == v {
			return true
		}
	}
	return false
}
