// Code generated by "enumer -type=Logic"; DO NOT EDIT.

package logic

import (
	"fmt"
	"strings"
)

const _LogicName = "GlitchlessGlitchedNoLogicVanilla"

var _LogicIndex = [...]uint8{0, 10, 18, 25, 32}

const _LogicLowerName = "glitchlessglitchednologicvanilla"

func (i Logic) String() string {
	if i < 0 || i >= Logic(len(_LogicIndex)-1) {
		return fmt.Sprintf("Logic(%d)", i)
	}
	return _LogicName[_LogicIndex[i]:_LogicIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _LogicNoOp() {
	var x [1]struct{}
	_ = x[Glitchless-(0)]
	_ = x[Glitched-(1)]
	_ = x[NoLogic-(2)]
	_ = x[Vanilla-(3)]
}

var _LogicValues = []Logic{Glitchless, Glitched, NoLogic, Vanilla}

var _LogicNameToValueMap = map[string]Logic{
	_LogicName[0:10]:       Glitchless,
	_LogicLowerName[0:10]:  Glitchless,
	_LogicName[10:18]:      Glitched,
	_LogicLowerName[10:18]: Glitched,
	_LogicName[18:25]:      NoLogic,
	_LogicLowerName[18:25]: NoLogic,
	_LogicName[25:32]:      Vanilla,
	_LogicLowerName[25:32]: Vanilla,
}

var _LogicNames = []string{
	_LogicName[0:10],
	_LogicName[10:18],
	_LogicName[18:25],
	_LogicName[25:32],
}

// LogicString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func LogicString(s string) (Logic, error) {
	if val, ok := _LogicNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _LogicNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Logic values", s)
}

// LogicValues returns all values of the enum
func LogicValues() []Logic {
	return _LogicValues
}

// LogicStrings returns a slice of all String values of the enum
func LogicStrings() []string {
	strs := make([]string, len(_LogicNames))
	copy(strs, _LogicNames)
	return strs
}

// IsALogic returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Logic) IsALogic() bool {
	for _, v := range _LogicValues {
		if i == v {
			return true
		}
	}
	return false
}
