// Code generated by "enumer -type=Scrubsanity"; DO NOT EDIT.

package scrubsanity

import (
	"fmt"
	"strings"
)

const _ScrubsanityName = "OffAffordableExpensiveRandomPrices"

var _ScrubsanityIndex = [...]uint8{0, 3, 13, 22, 34}

const _ScrubsanityLowerName = "offaffordableexpensiverandomprices"

func (i Scrubsanity) String() string {
	if i < 0 || i >= Scrubsanity(len(_ScrubsanityIndex)-1) {
		return fmt.Sprintf("Scrubsanity(%d)", i)
	}
	return _ScrubsanityName[_ScrubsanityIndex[i]:_ScrubsanityIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ScrubsanityNoOp() {
	var x [1]struct{}
	_ = x[Off-(0)]
	_ = x[Affordable-(1)]
	_ = x[Expensive-(2)]
	_ = x[RandomPrices-(3)]
}

var _ScrubsanityValues = []Scrubsanity{Off, Affordable, Expensive, RandomPrices}

var _ScrubsanityNameToValueMap = map[string]Scrubsanity{
	_ScrubsanityName[0:3]:        Off,
	_ScrubsanityLowerName[0:3]:   Off,
	_ScrubsanityName[3:13]:       Affordable,
	_ScrubsanityLowerName[3:13]:  Affordable,
	_ScrubsanityName[13:22]:      Expensive,
	_ScrubsanityLowerName[13:22]: Expensive,
	_ScrubsanityName[22:34]:      RandomPrices,
	_ScrubsanityLowerName[22:34]: RandomPrices,
}

var _ScrubsanityNames = []string{
	_ScrubsanityName[0:3],
	_ScrubsanityName[3:13],
	_ScrubsanityName[13:22],
	_ScrubsanityName[22:34],
}

// ScrubsanityString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ScrubsanityString(s string) (Scrubsanity, error) {
	if val, ok := _ScrubsanityNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ScrubsanityNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Scrubsanity values", s)
}

// ScrubsanityValues returns all values of the enum
func ScrubsanityValues() []Scrubsanity {
	return _ScrubsanityValues
}

// ScrubsanityStrings returns a slice of all String values of the enum
func ScrubsanityStrings() []string {
	strs := make([]string, len(_ScrubsanityNames))
	copy(strs, _ScrubsanityNames)
	return strs
}

// IsAScrubsanity returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Scrubsanity) IsAScrubsanity() bool {
	for _, v := range _ScrubsanityValues {
		if i == v {
			return true
		}
	}
	return false
}
